{
  "pipeline_name": "Rat Hindlimb Biomechanics Pipeline",
  "unscaled_model": "models/osim/FinalBilateral_millard_tsl_gait.osim",
  "marker_set": "models/osim/rat_hindlimb_bilateral_markerset.xml",
  "scale_setup": "models/osim/rat_hindlimb_bilateral_scale_setup.xml",
  "ik_setup": "models/osim/rat_hindlimb_bilateral_ik_setup.xml",

  "required_markers": [
    "TAIL", "SPL6", "LASI", "RASI",  # Torso
    "LHIP", "LKNE", "LANK", "LTOE",  # Left leg
    "RHIP", "RKNE", "RANK", "RTOE"   # Right leg
  ],
  "required_parameters": [ 
    "Mass", "Length", "RFemurLength", "RTibiaLength", "RFootLength",
    "LFemurLength", "LTibiaLength", "LFootLength"
  ],

  "output_dir": "output"
}